home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path('', views.home, name= "home"),
    path('teklif-al/', views.offer, name= "offer"),
    #path('iletisim/', views.contact, name= "contact"),
    path('<slug:slug>/', views.blog_detail, name= "detail"),
    # path('about/', views.about, name= "about"),
]

kaan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from home.sitemaps import BlogSitemap, StaticViewSitemap


sitemaps = {
	'blogs' : BlogSitemap,
    'static': StaticViewSitemap,

}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type ="text/plain")),   
    path('google42bbd82ce6dc94c4.html/', TemplateView.as_view(template_name="google42bbd82ce6dc94c4.html", content_type ="text/plain")),   
    path('yandex_5f9e6d82bf483a38.html/', TemplateView.as_view(template_name="yandex_5f9e6d82bf483a38.html", content_type ="text/plain")),   
    path('sitemap.xml/', sitemap, {'sitemaps':sitemaps}),
]

if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
  <!-- ======= Footer ======= -->
  <footer>
    <div class="footer-area">
      <div class="container">
        <div class="row">

          <!-- end single footer -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="footer-content">
              <div class="footer-head">
                <h4>İLETİŞİM</h4>

                <div class="footer-contacts">
              
                  <p><span class = "text-danger">Adres:</span>  {{setting.adress}}</p>
                  <p><span class = "text-danger">Tel:</span> {{setting.phone}}</p>
                  <p><span class = "text-danger">Email:</span> {{setting.email}}</p>
                </div>
              </div>
            </div>
          </div>
          <!-- end single footer -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="footer-content">
              <div class="footer-head">
                <h4>FAYDALI LİNKLER</h4>

                <div class="footer-contacts">
                  <p><span><a href="{% url 'home:home' %}" class = "text-danger">Anasayfa</a></span></p>
                  {% for about in abouts %}
                  <p><span><a href="{{about.get_absolute_url}}" class = "text-danger">{{about.title}}</a></span></p>

                  {% endfor %}

                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="footer-content">
              <div class="footer-head">
                <div class="footer-logo">
                  <h2><span>KAAN</span> | FİLO </h2>
                </div>

                <div class="footer-icons">
                  <ul>
                    <li>
                      <a  href="{{setting.instagram_url}}"><i class="fa fa-instagram"></i></a>
                    </li>
                    <li>
                      <a href="{{setting.twitter_url}}"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li>
                      <a href="{{setting.facebook_url}}"><i class="fa fa-facebook"></i></a>
                    </li>
                   

                  </ul>
                </div>
              </div>
            </div>
          </div>
          <!-- <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="footer-content">
              <div class="footer-head">
                <h4>Instagram</h4>
                <div class="flicker-img">
                  <a href="#"><img src="assets/img/portfolio/1.jpg" alt=""></a>
                  <a href="#"><img src="assets/img/portfolio/2.jpg" alt=""></a>
                  <a href="#"><img src="assets/img/portfolio/3.jpg" alt=""></a>
                  <a href="#"><img src="assets/img/portfolio/4.jpg" alt=""></a>
                  <a href="#"><img src="assets/img/portfolio/5.jpg" alt=""></a>
                  <a href="#"><img src="assets/img/portfolio/6.jpg" alt=""></a>
                </div>
              </div>
            </div>
          </div> -->


        </div>
      </div>
    </div>
    <div class="footer-area-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="copyright text-center">
              <p>
                &copy; Copyright <strong><span>{{setting.copyright_name}}</span></strong>Tüm hakları saklıdır.
              </p>
            </div>
            <div class="credits">
              <!--
              All the links in the footer should remain intact.
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=eBusiness
            -->
              <!-- Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  

  
  <!-- End  Footer -->
  <!-- End  Footer -->

templates/includes/messages.html
{% if messages %}
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  {{ message }}
</div>
{% endfor %}

{%endif %}

templates/includes/navbar.html
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="{% url 'home:home' %}"><span>KAAN</span> | FİLO </a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="#header"></a></li>
          <li class="drop-down"><a href="{% url 'home:home' %}#about">Hakkımızda</a>
            <ul>
              
              {% for about in abouts  %}
                
              <li><a href="{{about.get_absolute_url}}">{{about.title}}</a></li>
              {% endfor %}
                 
            
            </ul>
          </li>
          <li><a href="{% url 'home:offer' %}">Teklif Al</a></li>
          <li class="drop-down"><a href="{% url 'home:home' %}#services">Hizmetlerimiz</a>
            <ul>
              {% for renting in rentings  %}
                
              <li><a href="{{renting.get_absolute_url}}">{{renting.title}}</a></li>
              {% endfor %}

            </ul>
          </li>            
          <!-- <li><a href="{% url 'home:home' %}#team">Kiralık Sraçlarımız</a></li> -->
            <!-- <li><a href="{% url 'home:home' %}#portfolio">Araçlarımız</a></li> -->
          <li><a href="{% url 'home:home' %}#contact">İletişim</a></li>

        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->